# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- releases/*


pool:
  vmImage: "windows-latest"

stages:
-  stage: Montar
   jobs:
   - job: Tareas
     steps:
     - task: Maven@3
       inputs:
        mavenPomFile: "pom.xml"
        mavenOptions: "-Xmx3072m"
        javaHomeOption: "JDKVersion"
        jdkVersionOption: "1.10"
        jdkArchitectureOption: "x64"
        publishJUnitResults: true
        testResultsFiles: "**/TEST-*.xml"
        goals: "package"
     - task: PublishCodeCoverageResults@1
       inputs:
        codeCoverageTool: "JaCoCo"
        summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/site/jacoco/jacoco.xml"
        reportDirectory: "$(System.DefaultWorkingDirectory)/**/site/jacoco"
        failIfCoverageEmpty: true

-  stage: deploy
   jobs:
   - deployment: DeployWeb
     displayName: deploy Web App
     pool:
      vmImage: 'Ubuntu-latest'
    # creates an environment if it doesn't exist
     environment: 'smarthotel-dev'
     strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world